import { Question } from "@/store/useUserStore";

export const SAMPLE_QUESTIONS: Question[] = [
  // QA Questions
  {
    id: 1,
    text: "If the sum of three consecutive integers is 84, what is the largest integer?",
    options: ["27", "28", "29", "30"],
    correctAnswer: 2,
    section: "qa",
    topic: "Arithmetic",
    difficulty: "beginner",
    explanation: "Let the three consecutive integers be n-1, n, n+1. Their sum = 3n = 84, so n = 28. The largest integer is n+1 = 29.",
    timeToSolve: 60,
  },
  {
    id: 2,
    text: "A train travels from A to B at 60 km/h and returns from B to A at 40 km/h. What is the average speed for the entire journey?",
    options: ["48 km/h", "50 km/h", "52 km/h", "45 km/h"],
    correctAnswer: 0,
    section: "qa",
    topic: "Time-Speed-Distance",
    difficulty: "intermediate",
    explanation: "Average speed = 2×60×40/(60+40) = 4800/100 = 48 km/h. Use harmonic mean for equal distances at different speeds.",
    timeToSolve: 90,
  },
  {
    id: 3,
    text: "How many ways can 6 people be seated in a row if 2 specific people must always sit together?",
    options: ["120", "240", "360", "720"],
    correctAnswer: 1,
    section: "qa",
    topic: "Permutation & Combination",
    difficulty: "intermediate",
    explanation: "Treat the 2 people as one unit. Now we have 5 units to arrange = 5! = 120 ways. The 2 people can swap = 2! = 2 ways. Total = 120 × 2 = 240.",
    timeToSolve: 120,
  },
  {
    id: 4,
    text: "If log₂(x) + log₂(x+2) = 3, find x.",
    options: ["1", "2", "3", "4"],
    correctAnswer: 1,
    section: "qa",
    topic: "Algebra",
    difficulty: "advanced",
    explanation: "log₂(x(x+2)) = 3, so x(x+2) = 8. x² + 2x - 8 = 0. (x+4)(x-2) = 0. Since x > 0, x = 2.",
    timeToSolve: 150,
  },
  {
    id: 5,
    text: "What is the remainder when 7^100 is divided by 48?",
    options: ["1", "7", "36", "43"],
    correctAnswer: 0,
    section: "qa",
    topic: "Number System",
    difficulty: "cat level",
    explanation: "7² = 49 = 48 + 1 ≡ 1 (mod 48). So 7^100 = (7²)^50 ≡ 1^50 = 1 (mod 48). Remainder = 1.",
    timeToSolve: 180,
  },
  // VARC Questions
  {
    id: 6,
    text: "Choose the sentence that CANNOT be part of the sequence: \nA. The industrial revolution transformed society.\nB. Factories replaced cottage industries.\nC. The sky is blue on sunny days.\nD. Workers migrated to urban centers.",
    options: ["A", "B", "C", "D"],
    correctAnswer: 2,
    section: "varc",
    topic: "Odd One Out",
    difficulty: "intermediate",
    explanation: "Sentences A, B, and D are all related to the industrial revolution and its effects. Sentence C about the sky being blue is completely unrelated to this theme.",
    timeToSolve: 90,
  },
  {
    id: 7,
    text: "Read the passage: 'Despite the proliferation of social media, genuine human connection has become increasingly rare. People curate their lives for public consumption, presenting idealized versions that bear little resemblance to reality.' What is the author's primary concern?",
    options: [
      "Social media's role in spreading misinformation",
      "The superficiality fostered by social media culture",
      "The technical challenges of social platforms",
      "Economic impacts of social media companies"
    ],
    correctAnswer: 1,
    section: "varc",
    topic: "Reading Comprehension",
    difficulty: "intermediate",
    explanation: "The passage focuses on how social media creates a superficial culture where people present idealized rather than authentic versions of themselves, leading to loss of genuine connection.",
    timeToSolve: 120,
  },
  // DILR Questions
  {
    id: 8,
    text: "In a group of 5 people (A, B, C, D, E) sitting in a circle, B sits two places to the right of A. C sits opposite to A. D is adjacent to C. Where does E sit relative to A?",
    options: [
      "Immediately to the left of A",
      "Immediately to the right of A",
      "Opposite to B",
      "Between B and C"
    ],
    correctAnswer: 0,
    section: "dilr",
    topic: "Seating Arrangement",
    difficulty: "intermediate",
    explanation: "Placing A at position 1: B is at position 3 (two right). C opposite A is at position... In a circle of 5, 'opposite' means 2-3 positions away. Working through the arrangement, E ends up immediately to the left of A.",
    timeToSolve: 180,
  },
];

export const EXAM_DETAILS = [
  {
    name: "CAT",
    fullName: "Common Admission Test",
    conductedBy: "IIMs",
    duration: "120 minutes",
    sections: ["VARC", "DILR", "QA"],
    questions: 66,
    colleges: "20 IIMs + 100+ institutes",
    examDate: "November 24, 2024",
    color: "from-blue-600 to-cyan-500",
  },
  {
    name: "XAT",
    fullName: "Xavier Aptitude Test",
    conductedBy: "XLRI",
    duration: "190 minutes",
    sections: ["VALR", "DM", "QA&DI", "GK"],
    questions: 105,
    colleges: "XLRI + 160+ B-schools",
    examDate: "January 5, 2025",
    color: "from-purple-600 to-pink-500",
  },
  {
    name: "SNAP",
    fullName: "Symbiosis National Aptitude Test",
    conductedBy: "Symbiosis",
    duration: "60 minutes",
    sections: ["General English", "Analytical & LR", "Quantitative"],
    questions: 60,
    colleges: "Symbiosis institutes",
    examDate: "December 2024",
    color: "from-green-600 to-teal-500",
  },
  {
    name: "NMAT",
    fullName: "NMIMS Management Aptitude Test",
    conductedBy: "GMAC",
    duration: "120 minutes",
    sections: ["Language Skills", "Quantitative Skills", "Logical Reasoning"],
    questions: 108,
    colleges: "NMIMS + other institutes",
    examDate: "Oct–Dec 2024",
    color: "from-orange-600 to-red-500",
  },
  {
    name: "IIFT",
    fullName: "Indian Institute of Foreign Trade",
    conductedBy: "NTA",
    duration: "120 minutes",
    sections: ["VA", "RC", "QA", "DI&LR", "GK"],
    questions: 110,
    colleges: "IIFT Delhi, Kolkata, Kakinada",
    examDate: "December 2024",
    color: "from-yellow-600 to-orange-500",
  },
  {
    name: "MICAT",
    fullName: "MICA Admission Test",
    conductedBy: "MICA",
    duration: "165 minutes",
    sections: ["RA", "Psychometric", "Divergent Thinking", "Verbal"],
    questions: 150,
    colleges: "MICA Ahmedabad",
    examDate: "December 2024",
    color: "from-pink-600 to-rose-500",
  },
];

export const TOPICS = {
  qa: [
    { name: "Arithmetic", subtopics: ["Percentages", "Profit & Loss", "SI & CI", "Ratios", "Averages"], mastery: 72 },
    { name: "Algebra", subtopics: ["Linear Equations", "Quadratic", "Logarithms", "Functions"], mastery: 58 },
    { name: "Geometry", subtopics: ["Triangles", "Circles", "Mensuration", "Coordinate Geometry"], mastery: 45 },
    { name: "Number System", subtopics: ["Divisibility", "Remainders", "HCF & LCM", "Factorials"], mastery: 80 },
    { name: "P&C + Probability", subtopics: ["Permutations", "Combinations", "Probability"], mastery: 35 },
    { name: "TSD + Work", subtopics: ["Speed-Distance", "Trains", "Boats", "Work & Time"], mastery: 65 },
    { name: "Modern Math", subtopics: ["Sets", "Functions", "Sequences", "Progressions"], mastery: 55 },
  ],
  varc: [
    { name: "Reading Comprehension", subtopics: ["Inference", "Main Idea", "Vocabulary in Context", "Tone"], mastery: 68 },
    { name: "Para Jumbles", subtopics: ["Sentence ordering", "Opening/Closing sentences"], mastery: 52 },
    { name: "Odd Sentence Out", subtopics: ["Theme identification", "Context matching"], mastery: 75 },
    { name: "Para Summary", subtopics: ["Central idea", "Author's intent"], mastery: 60 },
    { name: "Vocabulary", subtopics: ["Word meaning", "Synonyms", "Antonyms", "Contextual usage"], mastery: 70 },
  ],
  dilr: [
    { name: "Data Interpretation", subtopics: ["Tables", "Bar charts", "Line graphs", "Pie charts", "Caselets"], mastery: 62 },
    { name: "Logical Reasoning", subtopics: ["Seating arrangements", "Puzzles", "Grid-based", "Venn diagrams"], mastery: 48 },
    { name: "Games & Tournaments", subtopics: ["Knockout", "Round robin", "Cricket scoring"], mastery: 40 },
  ],
};
