export type MockCategory =
  | "Full"
  | "Sectional"
  | "Adaptive"
  | "Speed"
  | "Topic"
  | "Beginner"
  | "Intermediate"
  | "Advanced"
  | "PYQ"
  | "Mini"
  | "Marathon"
  | "XAT";

export type MockDifficulty = "Starter" | "Intermediate" | "Advanced" | "CAT Level" | "Dynamic" | "Mixed";
export type MockSection = "VARC" | "DILR" | "QA" | "All";
export type MockLabel = "trending" | "new" | "ai-recommended" | "most-attempted" | "limited" | "popular";

export interface MockTest {
  id: number;
  name: string;
  category: MockCategory;
  section: MockSection;
  difficulty: MockDifficulty;
  questions: number;
  /** minutes */
  duration: number;
  attempts: number;
  bestPercentile: number | null;
  avgAccuracy: number | null;
  /** Estimated percentile jump if completed */
  percentileGain: number | null;
  labels: MockLabel[];
  description: string;
  /** XP awarded on first completion */
  xpReward: number;
  /** Percentile target range shown on card */
  targetPercentile: string;
  /** Topic covered, for topic-type tests */
  topic?: string;
}

export const MOCK_TESTS: MockTest[] = [
  // ── Full Mocks ────────────────────────────────────────────────────────────
  {
    id: 1,
    name: "CAT Full Mock #1",
    category: "Full",
    section: "All",
    difficulty: "CAT Level",
    questions: 66,
    duration: 120,
    attempts: 2,
    bestPercentile: 88.5,
    avgAccuracy: 74,
    percentileGain: 3,
    labels: ["most-attempted"],
    description: "Full-length CAT simulation with all three sections at authentic difficulty.",
    xpReward: 200,
    targetPercentile: "85–92",
  },
  {
    id: 2,
    name: "CAT Full Mock #2",
    category: "Full",
    section: "All",
    difficulty: "CAT Level",
    questions: 66,
    duration: 120,
    attempts: 1,
    bestPercentile: 91.2,
    avgAccuracy: 80,
    percentileGain: 4,
    labels: ["trending", "ai-recommended"],
    description: "Harder QA section — designed to stress-test arithmetic and geometry speed.",
    xpReward: 200,
    targetPercentile: "88–95",
  },
  {
    id: 3,
    name: "CAT Full Mock #3",
    category: "Full",
    section: "All",
    difficulty: "CAT Level",
    questions: 66,
    duration: 120,
    attempts: 0,
    bestPercentile: null,
    avgAccuracy: null,
    percentileGain: 5,
    labels: ["new"],
    description: "VARC-heavy mock with dense RC passages and tricky para-jumbles.",
    xpReward: 200,
    targetPercentile: "87–94",
  },
  {
    id: 4,
    name: "CAT Full Mock #4 — Elite",
    category: "Full",
    section: "All",
    difficulty: "CAT Level",
    questions: 66,
    duration: 120,
    attempts: 0,
    bestPercentile: null,
    avgAccuracy: null,
    percentileGain: 6,
    labels: ["new", "ai-recommended"],
    description: "Elite-level mock targeting 98–99 percentile aspirants. Maximum difficulty.",
    xpReward: 250,
    targetPercentile: "95–99",
  },

  // ── Sectional Mocks ───────────────────────────────────────────────────────
  {
    id: 5,
    name: "VARC Sectional #1",
    category: "Sectional",
    section: "VARC",
    difficulty: "Advanced",
    questions: 24,
    duration: 40,
    attempts: 3,
    bestPercentile: 78,
    avgAccuracy: 68,
    percentileGain: 2,
    labels: ["most-attempted"],
    description: "3 RC passages + 6 verbal reasoning questions. Focus on inference skills.",
    xpReward: 100,
    targetPercentile: "75–85",
  },
  {
    id: 6,
    name: "VARC Sectional #2 — RC Sprint",
    category: "Sectional",
    section: "VARC",
    difficulty: "CAT Level",
    questions: 24,
    duration: 40,
    attempts: 0,
    bestPercentile: null,
    avgAccuracy: null,
    percentileGain: 3,
    labels: ["new"],
    description: "4 long RC passages. Tests sustained reading speed and comprehension depth.",
    xpReward: 100,
    targetPercentile: "80–90",
  },
  {
    id: 7,
    name: "DILR Sectional #1",
    category: "Sectional",
    section: "DILR",
    difficulty: "Advanced",
    questions: 20,
    duration: 40,
    attempts: 1,
    bestPercentile: 65,
    avgAccuracy: 58,
    percentileGain: 4,
    labels: ["ai-recommended"],
    description: "2 DI caselets + 2 LR sets. Caselet-heavy design mirrors recent CAT patterns.",
    xpReward: 100,
    targetPercentile: "70–80",
  },
  {
    id: 8,
    name: "DILR Sectional #2 — Puzzle Edition",
    category: "Sectional",
    section: "DILR",
    difficulty: "CAT Level",
    questions: 20,
    duration: 40,
    attempts: 0,
    bestPercentile: null,
    avgAccuracy: null,
    percentileGain: 5,
    labels: ["new", "trending"],
    description: "Games & Tournament + Grid-based puzzles. Tests lateral thinking under pressure.",
    xpReward: 120,
    targetPercentile: "75–88",
  },
  {
    id: 9,
    name: "QA Sectional #1",
    category: "Sectional",
    section: "QA",
    difficulty: "Advanced",
    questions: 22,
    duration: 40,
    attempts: 0,
    bestPercentile: null,
    avgAccuracy: null,
    percentileGain: 4,
    labels: ["new"],
    description: "Arithmetic + Algebra heavy. Strong shortcut-application required.",
    xpReward: 100,
    targetPercentile: "78–88",
  },

  // ── Adaptive Mocks ────────────────────────────────────────────────────────
  {
    id: 10,
    name: "Adaptive Mock #1",
    category: "Adaptive",
    section: "All",
    difficulty: "Dynamic",
    questions: 40,
    duration: 60,
    attempts: 1,
    bestPercentile: 85,
    avgAccuracy: 76,
    percentileGain: 5,
    labels: ["ai-recommended", "trending"],
    description: "AI adjusts difficulty in real time based on your answer pattern. Reveals true level.",
    xpReward: 180,
    targetPercentile: "80–95",
  },
  {
    id: 11,
    name: "Adaptive Mock #2 — VARC Focus",
    category: "Adaptive",
    section: "VARC",
    difficulty: "Dynamic",
    questions: 24,
    duration: 40,
    attempts: 0,
    bestPercentile: null,
    avgAccuracy: null,
    percentileGain: 6,
    labels: ["new", "ai-recommended"],
    description: "Adaptive VARC session — harder passages unlock as you answer correctly.",
    xpReward: 150,
    targetPercentile: "82–96",
  },
  {
    id: 12,
    name: "Adaptive Mock #3 — QA Ladder",
    category: "Adaptive",
    section: "QA",
    difficulty: "Dynamic",
    questions: 25,
    duration: 45,
    attempts: 0,
    bestPercentile: null,
    avgAccuracy: null,
    percentileGain: 7,
    labels: ["ai-recommended"],
    description: "Starts at medium difficulty. Each correct answer escalates to a harder tier.",
    xpReward: 150,
    targetPercentile: "83–98",
  },

  // ── Speed Tests ───────────────────────────────────────────────────────────
  {
    id: 13,
    name: "QA Speed Challenge",
    category: "Speed",
    section: "QA",
    difficulty: "Mixed",
    questions: 30,
    duration: 30,
    attempts: 0,
    bestPercentile: null,
    avgAccuracy: null,
    percentileGain: 3,
    labels: [],
    description: "1 min per question. Arithmetic, Algebra, Number System. Build calculation speed.",
    xpReward: 120,
    targetPercentile: "80–92",
  },
  {
    id: 14,
    name: "VARC Speed Sprint",
    category: "Speed",
    section: "VARC",
    difficulty: "Mixed",
    questions: 20,
    duration: 20,
    attempts: 0,
    bestPercentile: null,
    avgAccuracy: null,
    percentileGain: 2,
    labels: ["trending"],
    description: "Para Jumbles + Odd One Out blitz. 1 min per question, no time to overthink.",
    xpReward: 100,
    targetPercentile: "75–88",
  },
  {
    id: 15,
    name: "DILR Speed Blitz",
    category: "Speed",
    section: "DILR",
    difficulty: "Advanced",
    questions: 16,
    duration: 20,
    attempts: 0,
    bestPercentile: null,
    avgAccuracy: null,
    percentileGain: 3,
    labels: ["new"],
    description: "4 mini sets of 4 questions each. Decision-making under maximum time pressure.",
    xpReward: 110,
    targetPercentile: "78–90",
  },

  // ── Topic Tests ───────────────────────────────────────────────────────────
  {
    id: 16,
    name: "QA Topic — Number System",
    category: "Topic",
    section: "QA",
    difficulty: "Intermediate",
    questions: 20,
    duration: 25,
    attempts: 2,
    bestPercentile: null,
    avgAccuracy: 72,
    percentileGain: null,
    labels: ["most-attempted"],
    description: "Divisibility, remainders, HCF/LCM, unit digits, cyclicity. 20 targeted questions.",
    xpReward: 80,
    targetPercentile: "80–90",
    topic: "Number System",
  },
  {
    id: 17,
    name: "QA Topic — Geometry",
    category: "Topic",
    section: "QA",
    difficulty: "Advanced",
    questions: 20,
    duration: 30,
    attempts: 0,
    bestPercentile: null,
    avgAccuracy: null,
    percentileGain: null,
    labels: ["ai-recommended"],
    description: "Circles, triangles, polygons, coordinate geometry. Property-first approach tested.",
    xpReward: 80,
    targetPercentile: "82–92",
    topic: "Geometry",
  },
  {
    id: 18,
    name: "QA Topic — Algebra",
    category: "Topic",
    section: "QA",
    difficulty: "Intermediate",
    questions: 18,
    duration: 25,
    attempts: 1,
    bestPercentile: null,
    avgAccuracy: 65,
    percentileGain: null,
    labels: [],
    description: "Quadratics, functions, inequalities, modulus. Core algebra drill.",
    xpReward: 80,
    targetPercentile: "78–88",
    topic: "Algebra",
  },
  {
    id: 19,
    name: "VARC Topic — Para Jumbles",
    category: "Topic",
    section: "VARC",
    difficulty: "Intermediate",
    questions: 15,
    duration: 20,
    attempts: 0,
    bestPercentile: null,
    avgAccuracy: null,
    percentileGain: null,
    labels: ["ai-recommended"],
    description: "15 Para Jumble questions across 3 difficulty tiers. Master the 3-step framework.",
    xpReward: 70,
    targetPercentile: "75–85",
    topic: "Para Jumbles",
  },
  {
    id: 20,
    name: "DILR Topic — Seating Arrangement",
    category: "Topic",
    section: "DILR",
    difficulty: "Advanced",
    questions: 16,
    duration: 25,
    attempts: 0,
    bestPercentile: null,
    avgAccuracy: null,
    percentileGain: null,
    labels: [],
    description: "4 complete seating arrangement sets: linear, circular, double-row, complex.",
    xpReward: 80,
    targetPercentile: "80–90",
    topic: "Seating Arrangement",
  },
  {
    id: 21,
    name: "QA Topic — Probability & P&C",
    category: "Topic",
    section: "QA",
    difficulty: "Advanced",
    questions: 18,
    duration: 25,
    attempts: 0,
    bestPercentile: null,
    avgAccuracy: null,
    percentileGain: null,
    labels: ["new"],
    description: "Permutation, Combination, and Probability. Frequently tested in CAT.",
    xpReward: 80,
    targetPercentile: "80–90",
    topic: "Probability & P&C",
  },

  // ── Beginner Mocks ────────────────────────────────────────────────────────
  {
    id: 22,
    name: "Beginner Mock #1",
    category: "Beginner",
    section: "All",
    difficulty: "Starter",
    questions: 45,
    duration: 90,
    attempts: 0,
    bestPercentile: null,
    avgAccuracy: null,
    percentileGain: null,
    labels: ["popular"],
    description: "Your first full CAT simulation. Accessible difficulty — build confidence and exam habit.",
    xpReward: 150,
    targetPercentile: "60–75",
  },
  {
    id: 23,
    name: "Beginner Mock #2",
    category: "Beginner",
    section: "All",
    difficulty: "Starter",
    questions: 48,
    duration: 90,
    attempts: 0,
    bestPercentile: null,
    avgAccuracy: null,
    percentileGain: null,
    labels: [],
    description: "Slightly harder than #1. Focus on accuracy and avoiding negative marking.",
    xpReward: 150,
    targetPercentile: "65–78",
  },

  // ── Intermediate Mocks ────────────────────────────────────────────────────
  {
    id: 24,
    name: "Intermediate Mock #1",
    category: "Intermediate",
    section: "All",
    difficulty: "Intermediate",
    questions: 60,
    duration: 110,
    attempts: 0,
    bestPercentile: null,
    avgAccuracy: null,
    percentileGain: 5,
    labels: ["popular"],
    description: "Balanced CAT-level test. Target score: 120+. Bridge from beginner to advanced.",
    xpReward: 175,
    targetPercentile: "78–88",
  },
  {
    id: 25,
    name: "Intermediate Mock #2 — DILR Focus",
    category: "Intermediate",
    section: "All",
    difficulty: "Intermediate",
    questions: 60,
    duration: 110,
    attempts: 0,
    bestPercentile: null,
    avgAccuracy: null,
    percentileGain: 6,
    labels: ["ai-recommended"],
    description: "Harder DILR section to push aspirants into the 80–90 percentile band.",
    xpReward: 175,
    targetPercentile: "80–90",
  },

  // ── Advanced Mocks ────────────────────────────────────────────────────────
  {
    id: 26,
    name: "Advanced Mock #1 — 99 Percentile",
    category: "Advanced",
    section: "All",
    difficulty: "CAT Level",
    questions: 66,
    duration: 120,
    attempts: 0,
    bestPercentile: null,
    avgAccuracy: null,
    percentileGain: 8,
    labels: ["trending", "popular"],
    description: "Designed for 95–99 percentile aspirants. Brutal QA and complex DILR sets.",
    xpReward: 250,
    targetPercentile: "95–99",
  },
  {
    id: 27,
    name: "Advanced Mock #2 — Time Pressure",
    category: "Advanced",
    section: "All",
    difficulty: "CAT Level",
    questions: 66,
    duration: 110,
    attempts: 0,
    bestPercentile: null,
    avgAccuracy: null,
    percentileGain: 9,
    labels: ["new"],
    description: "Same question count, 10 min less. Forces elite-level time management.",
    xpReward: 275,
    targetPercentile: "96–99",
  },

  // ── Previous Year Simulations ─────────────────────────────────────────────
  {
    id: 28,
    name: "CAT 2021 Simulation",
    category: "PYQ",
    section: "All",
    difficulty: "CAT Level",
    questions: 66,
    duration: 120,
    attempts: 0,
    bestPercentile: null,
    avgAccuracy: null,
    percentileGain: 7,
    labels: ["popular"],
    description: "Authentic 2021 CAT question set — first slot. Post-COVID pattern with shorter VARC passages.",
    xpReward: 220,
    targetPercentile: "85–95",
  },
  {
    id: 29,
    name: "CAT 2022 Simulation",
    category: "PYQ",
    section: "All",
    difficulty: "CAT Level",
    questions: 66,
    duration: 120,
    attempts: 0,
    bestPercentile: null,
    avgAccuracy: null,
    percentileGain: 7,
    labels: ["trending"],
    description: "2022 slot 2 — hardest DILR year in recent CAT history. Key benchmark test.",
    xpReward: 220,
    targetPercentile: "85–96",
  },
  {
    id: 30,
    name: "CAT 2023 Simulation",
    category: "PYQ",
    section: "All",
    difficulty: "CAT Level",
    questions: 66,
    duration: 120,
    attempts: 0,
    bestPercentile: null,
    avgAccuracy: null,
    percentileGain: 8,
    labels: ["most-attempted", "trending"],
    description: "2023 pattern with integrated VARC + heavy data sets in DILR.",
    xpReward: 220,
    targetPercentile: "87–97",
  },
  {
    id: 31,
    name: "CAT 2024 Simulation",
    category: "PYQ",
    section: "All",
    difficulty: "CAT Level",
    questions: 66,
    duration: 120,
    attempts: 0,
    bestPercentile: null,
    avgAccuracy: null,
    percentileGain: 9,
    labels: ["new", "trending", "ai-recommended"],
    description: "Most recent CAT pattern. Closest approximation of this year's actual exam.",
    xpReward: 250,
    targetPercentile: "88–98",
  },

  // ── XAT / SNAP / NMAT ─────────────────────────────────────────────────────
  {
    id: 32,
    name: "XAT Mock #1",
    category: "XAT",
    section: "All",
    difficulty: "CAT Level",
    questions: 105,
    duration: 190,
    attempts: 0,
    bestPercentile: null,
    avgAccuracy: null,
    percentileGain: null,
    labels: ["popular"],
    description: "Full XAT simulation: VDRA + DM + QA + GK. Decision Making section included.",
    xpReward: 250,
    targetPercentile: "85–95",
  },
  {
    id: 33,
    name: "SNAP Mock #1",
    category: "XAT",
    section: "All",
    difficulty: "Intermediate",
    questions: 60,
    duration: 60,
    attempts: 0,
    bestPercentile: null,
    avgAccuracy: null,
    percentileGain: null,
    labels: [],
    description: "SNAP pattern: General English, Analytical & LR, Quantitative-DI. 60-minute sprint.",
    xpReward: 180,
    targetPercentile: "80–92",
  },

  // ── Daily Mini Mocks ──────────────────────────────────────────────────────
  {
    id: 34,
    name: "Daily Mini #1 — Morning Warm-up",
    category: "Mini",
    section: "All",
    difficulty: "Mixed",
    questions: 15,
    duration: 20,
    attempts: 0,
    bestPercentile: null,
    avgAccuracy: null,
    percentileGain: 1,
    labels: ["popular"],
    description: "Quick 20-minute daily practice shot. 5Q each from VARC, DILR, QA.",
    xpReward: 60,
    targetPercentile: "75–88",
  },
  {
    id: 35,
    name: "Daily Mini #2 — QA Drill",
    category: "Mini",
    section: "QA",
    difficulty: "Mixed",
    questions: 12,
    duration: 15,
    attempts: 0,
    bestPercentile: null,
    avgAccuracy: null,
    percentileGain: 1,
    labels: [],
    description: "Focused 15-min QA practice. Arithmetic, Algebra mix. Build daily momentum.",
    xpReward: 50,
    targetPercentile: "78–90",
  },
  {
    id: 36,
    name: "Daily Mini #3 — RC Focus",
    category: "Mini",
    section: "VARC",
    difficulty: "Mixed",
    questions: 10,
    duration: 15,
    attempts: 0,
    bestPercentile: null,
    avgAccuracy: null,
    percentileGain: 1,
    labels: ["ai-recommended"],
    description: "2 short RC passages. Perfect for building daily reading habit.",
    xpReward: 50,
    targetPercentile: "75–87",
  },

  // ── Marathon Mocks ────────────────────────────────────────────────────────
  {
    id: 37,
    name: "Weekend Marathon #1",
    category: "Marathon",
    section: "All",
    difficulty: "CAT Level",
    questions: 66,
    duration: 180,
    attempts: 0,
    bestPercentile: null,
    avgAccuracy: null,
    percentileGain: 10,
    labels: ["popular"],
    description: "3-hour ultra-realistic simulation with extended review. Full mock + 60-min analysis.",
    xpReward: 350,
    targetPercentile: "88–98",
  },
  {
    id: 38,
    name: "Weekend Marathon #2 — Stress Mode",
    category: "Marathon",
    section: "All",
    difficulty: "CAT Level",
    questions: 66,
    duration: 180,
    attempts: 0,
    bestPercentile: null,
    avgAccuracy: null,
    percentileGain: 12,
    labels: ["new", "trending"],
    description: "AI stress-pressure mode. Random interruptions simulate exam-hall distractions.",
    xpReward: 400,
    targetPercentile: "90–99",
  },
];

export const CATEGORY_META: Record<
  MockCategory,
  { label: string; color: string; icon: string; description: string }
> = {
  Full:         { label: "Full Mock",     color: "text-neon-blue bg-neon-blue/20 border-neon-blue/30",     icon: "🏆", description: "Full 120-min CAT simulation" },
  Sectional:    { label: "Sectional",     color: "text-purple-400 bg-purple-500/20 border-purple-500/30",  icon: "📋", description: "Section-wise targeted practice" },
  Adaptive:     { label: "Adaptive",      color: "text-yellow-400 bg-yellow-500/20 border-yellow-500/30",  icon: "🤖", description: "AI-driven adaptive difficulty" },
  Speed:        { label: "Speed Booster", color: "text-red-400 bg-red-500/20 border-red-500/30",           icon: "⚡", description: "Time-pressure intensive tests" },
  Topic:        { label: "Topic Tests",   color: "text-green-400 bg-green-500/20 border-green-500/30",     icon: "📚", description: "Deep-dive by specific topic" },
  Beginner:     { label: "Beginner",      color: "text-emerald-400 bg-emerald-500/20 border-emerald-500/30", icon: "🌱", description: "Confidence-building mocks" },
  Intermediate: { label: "Intermediate",  color: "text-orange-400 bg-orange-500/20 border-orange-500/30",  icon: "📈", description: "Balanced CAT-level practice" },
  Advanced:     { label: "Advanced",      color: "text-rose-400 bg-rose-500/20 border-rose-500/30",        icon: "🔥", description: "99 percentile-target mocks" },
  PYQ:          { label: "PYQ Simulations", color: "text-amber-400 bg-amber-500/20 border-amber-500/30",   icon: "📅", description: "Previous year CAT simulations" },
  Mini:         { label: "Daily Mini",    color: "text-teal-400 bg-teal-500/20 border-teal-500/30",        icon: "⏱️", description: "15–20 min daily practice" },
  Marathon:     { label: "Marathon",      color: "text-pink-400 bg-pink-500/20 border-pink-500/30",        icon: "🏃", description: "3-hour ultra-realistic tests" },
  XAT:          { label: "XAT / SNAP",   color: "text-indigo-400 bg-indigo-500/20 border-indigo-500/30",  icon: "🎓", description: "Multi-exam preparation" },
};

export const LABEL_META: Record<MockLabel, { text: string; color: string }> = {
  trending:       { text: "Trending",        color: "bg-orange-500/20 text-orange-400 border-orange-500/30" },
  new:            { text: "New",             color: "bg-green-500/15 text-green-400 border-green-500/25" },
  "ai-recommended": { text: "AI Pick",       color: "bg-neon-blue/15 text-neon-blue border-neon-blue/25" },
  "most-attempted": { text: "Most Tried",    color: "bg-purple-500/15 text-purple-400 border-purple-500/25" },
  limited:        { text: "Limited",         color: "bg-red-500/15 text-red-400 border-red-500/25" },
  popular:        { text: "Popular",         color: "bg-yellow-500/15 text-yellow-400 border-yellow-500/25" },
};

export const DIFFICULTY_COLOR: Record<MockDifficulty, string> = {
  Starter:      "text-emerald-400",
  Intermediate: "text-yellow-400",
  Advanced:     "text-orange-400",
  "CAT Level":  "text-red-400",
  Dynamic:      "text-neon-blue",
  Mixed:        "text-white/50",
};

export const DIFFICULTY_BAR: Record<MockDifficulty, number> = {
  Starter:      20,
  Intermediate: 45,
  Advanced:     70,
  "CAT Level":  92,
  Dynamic:      60,
  Mixed:        50,
};
